_wandb:
    value:
        cli_version: 0.23.1
        e:
            htc8yzdug9tdgutzol2b6tevhor9cnnk:
                apple:
                    ecpuCores: 2
                    gpuCores: 16
                    memoryGb: 16
                    name: Apple M1 Pro
                    pcpuCores: 8
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "4294967296"
                codePath: src/plants/train.py
                codePathLocal: src/plants/train.py
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "994662584320"
                        used: "340926328832"
                email: s224186@student.dtu.dk
                executable: /Users/nicolaigarderhansen/Desktop/MLOps_plant_project/.venv/bin/python3
                git:
                    commit: 8e209d890c500137b4046b93e5ca853d66f9af96
                    remote: https://github.com/cruesli/MLOps_plant_project.git
                host: MacBook-Pro-tilhrende-Nicolai.local
                memory:
                    total: "17179869184"
                os: macOS-15.1.1-arm64-arm-64bit-Mach-O
                program: /Users/nicolaigarderhansen/Desktop/MLOps_plant_project/src/plants/train.py
                python: CPython 3.13.11
                root: /Users/nicolaigarderhansen/Desktop/MLOps_plant_project
                startedAt: "2026-01-12T10:36:30.385503Z"
                writerId: htc8yzdug9tdgutzol2b6tevhor9cnnk
        m: []
        python_version: 3.13.11
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
            "2":
                - 1
                - 5
                - 41
                - 53
            "3":
                - 16
            "4": 3.13.11
            "5": 0.23.1
            "8":
                - 2
            "12": 0.23.1
            "13": darwin-arm64
batch_size:
    value: 32
epochs:
    value: 5
lr:
    value: 0.001
