project: plant-project
entity: mlops_plant_group
method: grid
metric:
  name: final_accuracy
  goal: maximize
parameters:
  lr:
    values: [0.0001, 0.0003, 0.0005, 0.001]
  batch_size:
    values: [16, 32, 64]
  dropout:
    values: [0.0, 0.2, 0.4]
program: src/plants/train.py
command:
  - ${env}
  - uv
  - run
  - ${program}
  - experiments=class
